[package]
edition = "2021"
name = "winprint"
version = "0.1.0"

[dependencies]
lazy_static = "1.4.0"
scopeguard = "1.1"
thiserror = "1.0"

[dependencies.windows]
version = "0.54"
features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Graphics_Gdi",
    "Win32_System_Com",
    "Win32_Storage_Xps_Printing",
    "Win32_System_Threading",
    "Win32_Graphics_Printing",
]

[build-dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
flate2 = "1.0"
tar = "0.4"

[features]
default = ["pdfium"]
pdfium = []
