name: Test

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Rust toolchain
      uses: moonrepo/setup-rust@v1
      with:
        channel: stable
        bins: cargo-hack
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Test
      run: cargo hack test --all-targets --each-feature --verbose
